config/routes.rb
Rails.application.routes.draw do
  
  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search

  # Authentication routes
  resources :sessions
  resources :users
  get 'employees/new', to: 'employees#new', as: :signup
  get 'employees/edit', to: 'employees#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  # Time Shifts routes
  get 'shifts/time_clock', to: 'shifts#time_clock', as: :time_clock
  patch 'shifts/time_in', to: 'shifts#time_in', as: :time_in
  patch 'shifts/time_out', to: 'shifts#time_out', as: :time_out
  # Payroll routes
  get 'payrolls/store_form', to: 'payrolls#store_form', as: :store_form
  get 'payrolls/employee_form', to: 'payrolls#employee_form', as: :employee_form
  get 'payrolls/employee_payroll', to: 'payrolls#employee_payroll', as: :employee_payroll
  get 'payrolls/store_payroll', to: 'payrolls#store_payroll', as: :store_payroll

  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :stores, except: [:destroy]
  resources :employees
  resources :assignments
  resources :shifts
  resources :shift_jobs, only: [:destroy]
  resources :jobs, except: [:show]
  resources :pay_grades, except: [:destroy]
  resources :pay_grade_rates

  # Other custom routes
  #get 'shift_today', to: 'shifts#route_clock', as: :shift_today_path
  get 'shift_jobs/new', to: 'shift_jobs#new', as: :new_shift_job
  post 'shift_jobs', to: 'shift_jobs#create', as: :shift_jobs

  # You can have the root of your site routed with 'root'
  root 'home#index'
  
end

app/models/employee.rb
class Employee < ApplicationRecord
  include Validations
  include Deletions
  include Activeable::InstanceMethods
  extend Activeable::ClassMethods
  
  has_secure_password

  # Relationships
  has_many :assignments 
  has_many :stores, through: :assignments
  has_many :shifts, through: :assignments 
  has_many :pay_grades, through: :assignments
  has_many :pay_grade_rates, through: :pay_grades

  # Enums
  enum :role, { employee: 1, manager: 2, admin: 3 }, scopes: false, default: :employee, suffix: true

  # Scopes
  scope :younger_than_18, -> { where('date_of_birth > ?', 18.years.ago.to_date) }
  scope :is_18_or_older,  -> { where('date_of_birth <= ?', 18.years.ago.to_date) }
  scope :regulars,        -> { where('role = ?', roles['employee']) }
  scope :managers,        -> { where('role = ?', roles['manager']) }
  scope :admins,          -> { where('role = ?', roles['admin']) }
  scope :alphabetical,    -> { order('last_name, first_name') }

  # Validations
  validates_presence_of :first_name, :last_name, :ssn
  validates_date :date_of_birth, :on_or_before => lambda { 14.years.ago }, on_or_before_message: 'must be at least 14 years old'
  validates_format_of :phone, with: /\A(\d{10}|\(?\d{3}\)?[-. ]\d{3}[-.]\d{4})\z/, message: 'should be 10 digits (area code needed) and delimited with dashes only'
  validates_format_of :ssn, with: /\A\d{3}[- ]?\d{2}[- ]?\d{4}\z/, message: 'should be 9 digits and delimited with dashes only'
  validates_uniqueness_of :ssn
  # validates_inclusion_of :role, in: roles.keys, message: 'is not an option'
  # ... more validations for later phases
  validates :username, presence: true, uniqueness: { case_sensitive: false}
  validates_presence_of :role, on: :create
  validates_presence_of :password, on: :create 
  validates_presence_of :password_confirmation, on: :create 
  validates_confirmation_of :password, on: :create, message: 'does not match'
  validates_length_of :password, minimum: 4, message: 'must be at least 4 characters long', allow_blank: true

  # Other methods
  def name
    "#{last_name}, #{first_name}"
  end
  
  def proper_name
    "#{first_name} #{last_name}"
  end

  def over_18?
    date_of_birth.to_date < 18.years.ago.to_date
  end
  
  def age
    (Time.now.to_formatted_s(:number).to_i - date_of_birth.to_time.to_formatted_s(:number).to_i)/10e9.to_i
  end

  def current_assignment
    curr_assignment = self.assignments.current    
    return nil if curr_assignment.empty?
    curr_assignment.first   # return as a single object, not an array
  end

  # Add in methods for later phases for authentication and payment handling
  include EmployeePayment
  include EmployeeAuthentication

  # Callbacks
  before_save -> { strip_nondigits_from(:phone) }
  before_save -> { strip_nondigits_from(:ssn) }

  # ... additional callbacks in phases 4 & 5
  include EmployeeDeletion
  before_destroy -> { handle_deletion_request() }
  # after_rollback -> { handle_deletion_failure() }

end

app/controllers/employees_controller.rb
class EmployeesController <  ApplicationController
  before_action :check_login
  authorize_resource

  def index
    if current_user.manager_role?
      @active_employees = current_user.current_assignment.store.employees.active.all.paginate(page: params[:page]).per_page(15)
      @inactive_employees = current_user.current_assignment.store.employees.inactive.all.paginate(page: params[:page]).per_page(15)
    else
      @active_employees = Employee.active.all.paginate(page: params[:page]).per_page(15)
      @inactive_employees = Employee.inactive.all.paginate(page: params[:page]).per_page(15)
    end
  end

  def show
    @employee = Employee.find(params[:id])
    @current_assignment = @employee.current_assignment
    @other_assignments = @employee.assignments - [@current_assignment]
  end

  def new
    @employee = Employee.new
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      flash[:notice] = "Successfully added #{@employee.proper_name} as an employee."
      redirect_to @employee
    else
      render :new
    end
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      flash[:notice] = "Updated #{@employee.proper_name}'s information."
      redirect_to @employee
    else
      render :edit
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    if @employee.shifts.empty?
      @employee.destroy
      flash[:notice] = "Employee deleted."
      redirect_to employees_url
    else
      flash[:notice] = "Employee cannot be deleted because of previously worked shifts."
      render :show
    end
  end

  private
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :ssn, :phone, :date_of_birth, :role, :username, :password, :password_confirmation, :active)
    end
end

app/views/employees/_employee_data.html.erb
<div class="card">
  <div class="card-content">
    <h5>Employee Profile for <%= @employee.proper_name %></h5><br />

    <b>Phone:&nbsp;&nbsp;</b>
      <%= @employee.phone %><br /><br />

    <b>Date of Birth:&nbsp;&nbsp;</b>
      <%= @employee.date_of_birth.strftime("%B %d, %Y") %><br /><br />

    <b>Role:&nbsp;&nbsp;</b>
    <%= @employee.role %><br /><br />

    <b>Active in Cafe23?&nbsp;&nbsp;</b>
      <%= @employee.active ? "Yes" : "No" %><br><br><br>
  </div>
</div>

app/views/employees/_employee_fields.html.erb
<%= f.input :first_name, label_html: { class: 'active' } %>
<%= f.input :last_name, label_html: { class: 'active' } %>
<%= f.input :username, label_html: { class: 'active' } %>
<%= f.input :password, label_html: { class: 'active' } %>
<%= f.input :password_confirmation, label_html: { class: 'active' } %>
<%= f.input :role, collection: Employee::ROLES_LIST, include_blank: true %>
<%= f.input :phone, label_html: { class: 'active' } %>
<%= f.input :date_of_birth, label_html: { class: 'active' } %>
<%= f.input :ssn, label_html: { class: 'active' } %>
<%= f.input :active %>

app/views/employees/_employee_sidebar.html.erb
<div class="card white lighten-4">
  <div class="card-content">
    <span class="card-title">Employee Assignments</span>
    <% if @employee.assignments.empty? %>
      <p> No assignments available. </p>
    <% else %>
      <ul>
        <% for assignment in @employee.assignments %>
          <li>
            <% if can? :destroy, Assignment %>
              <%= link_to(assignment_path(assignment), class: 'remove', method: :delete) do %>
                x&nbsp;&nbsp;
              <% end %>
            <% end %>
            <%= link_to "#{assignment.start_date}, #{assignment.store.name}", assignment %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <% if can? :new, Assignment %>
    <div class="card-action">
      <%= link_to "Assign to Store", new_assignment_path(employee_id: @employee.id), class: 'waves-effect waves-light btn' %>
    </div>
  <% end %>
</div>

app/views/employees/index.html.erb
<h2>Employees</h2>

<% if can? :new, Employee %>
  <%= link_to "Add New Employee", new_employee_path, class: 'waves-effect waves-light btn' %> 
<% end %>
<% if can? [:employee_form, :employee_report, :employee_payroll], :payrolls_controller %>
  <%= link_to "Generate Employee Payroll", employee_form_path, class: 'waves-effect waves-light btn' %> 
<% end %>

<h3>Active Employees at Cafe23</h3>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Current Assignments</th>
      <th>Phone</th>
    </tr>
  </thead>
  <tbody>
    <% @active_employees.each do |employee| %>
      <tr>
        <td><%= link_to "#{employee.name}", employee_path(employee) %></td>
        <td>
          <% if employee.current_assignment %>
            <%= employee.current_assignment.store ? employee.current_assignment.store.name : 'n/a' %>
          <% else %>
            n/a
          <% end %>
        </td>        
        <td><%= number_to_phone(employee.phone, delimiter: '-') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Inactive Employees at Cafe23</h3>
<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @inactive_employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @employee, 
                                                        type_of_form: "New Employee",
                                                        fields: "employee_fields"} %>

app/views/employees/show.html.erb
<%= render partial: "partials/show_structure", locals: {model_name: "employee", 
                                                         object: @employee,
                                                         primary: "employee_data", 
                                                         secondary: nil,
                                                         sidebar: "employee_sidebar"} %>