config/routes.rb
Rails.application.routes.draw do
  
  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search

  # Authentication routes
  resources :sessions
  resources :users
  get 'employees/new', to: 'employees#new', as: :signup
  get 'employees/edit', to: 'employees#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  # Time Shifts routes
  get 'shifts/time_clock', to: 'shifts#time_clock', as: :time_clock
  patch 'shifts/time_in', to: 'shifts#time_in', as: :time_in
  patch 'shifts/time_out', to: 'shifts#time_out', as: :time_out
  # Payroll routes
  get 'payrolls/store_form', to: 'payrolls#store_form', as: :store_form
  get 'payrolls/employee_form', to: 'payrolls#employee_form', as: :employee_form
  get 'payrolls/employee_payroll', to: 'payrolls#employee_payroll', as: :employee_payroll
  get 'payrolls/store_payroll', to: 'payrolls#store_payroll', as: :store_payroll

  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :stores, except: [:destroy]
  resources :employees
  resources :assignments
  resources :shifts
  resources :shift_jobs, only: [:destroy]
  resources :jobs, except: [:show]
  resources :pay_grades, except: [:destroy]
  resources :pay_grade_rates

  # Other custom routes
  #get 'shift_today', to: 'shifts#route_clock', as: :shift_today_path
  get 'shift_jobs/new', to: 'shift_jobs#new', as: :new_shift_job
  post 'shift_jobs', to: 'shift_jobs#create', as: :shift_jobs

  # You can have the root of your site routed with 'root'
  root 'home#index'
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def privacy
  end

end

app/views/home/about.html.erb
<div id="main_content">
  <h3>About Us</h3>
  <%= link_to "About the Cafe23 Management System", about_path, class: 'waves-effect waves-light btn'%>
  <p>Cafe23 is a cafe chain selling amazing drinks.</p>
  <p> We are a newly-established, family-owned and operated business that has been serving up delicious coffee and tea drinks.
      We use only the freshest ingredients and our baristas are experts in their craft. Whether you're looking for a classic cup of 
      coffee or something more creative, we have something for everyone. </p>
  <p>We are proud to be a part of the community and we are committed 
     to providing our customers with the best possible experience. We hope to see you soon!</p>
</div>

app/views/home/contact.html.erb
<div id="main_content">
  <h3>Contact Us</h3>
  <p> Unfortunately, Cafe23 is not a real coffee chain, but rather a 
      sample project for programming students at Carnegie Mellon University.</p>
  <p>Even so, we'd love to hear from you! If you have any questions or comments, 
      please don't hesitate to reach out.</p>
</div>

app/views/home/index.html.erb
<div class="row">  
  <h3>Welcome to Cafe23!</h3><h2 style="display: inline;">☕</h2>

  <% if current_user %>
    <% if current_user.admin_role? %>
      <h5>Quick Actions:</h5>
      <%= link_to 'Payroll for Employee', employee_form_path, class: 'waves-effect waves-light btn' %>
      <br><br>
      <%= link_to 'Payroll for Store', store_form_path, class: 'waves-effect waves-light btn' %>
      <br><br>
      <%= link_to 'Create New Employee', new_employee_path, class: 'waves-effect waves-light btn' %>
    <% end %>

    <% if current_user.manager_role? %>
      <h5>Quick Actions:</h5>
      <%= link_to 'Payroll for Store', store_form_path, class: 'waves-effect waves-light btn' %>
      <br><br>
      <%= link_to 'Create New Shift', new_shift_path, class: 'waves-effect waves-light btn' %>
      <br><br>
      <%= link_to 'Record A Job', new_shift_job_path, class: 'waves-effect waves-light btn' %>
    <% end %>

    <% if current_user.employee_role? %>
      <h4>Below is a list of your upcoming shifts.</h4>
      <div class="card white lighten-4">
        <div class="card-content">
          <% if current_user.shifts.upcoming.empty? %>
            <p>You have no upcoming shifts!</p> 
          <% else %>
            <table class="striped highlight"> 
              <thead> 
                <th>Date</th>
                <th>Start Time</th> 
                <th>End Time</th> 
                <th>Clock In/Out</th> 
              </thead> 
              <tbody>
              <% for shift in current_user.shifts.upcoming.chronological %> 
                <tr> 
                  <td><%= shift.date.strftime("%B %d, %Y") %></td> 
                  <td><%= shift.start_time.strftime("%H:%M") %></td>
                  <td>
                    <% if shift.end_time.present? %>
                      <%= shift.end_time.strftime("%H:%M") %>
                    <% else %>
                      N/A
                    <% end %>
                  </td>
                  <td>
                    <% if shift.pending? && shift.date == Date.today %>
                      <%= link_to time_in_path, method: :patch do %>
                        <i class="button">Clock In</i> 
                      <% end %> 
                    <% elsif shift.started? %>
                      <%= link_to time_out_path, method: :patch do %>
                        <i class="button">Clock Out</i> 
                      <% end %>                    
                      <% elsif shift.finished? %>
                        <p>✅ Completed</p>
                      <% end %>
                  </td> 
                </tr> 
              </tbody>
              <% end %> 
            </table>
          <% end %>
        </div>
      </div>
    <% end %>

  <% else %>
    <p>We're a cafe chain that's passionate about coffee, food, and community. 
       We believe that great coffee can bring people together, and we're committed to providing our customers with the best possible experience.</p>
    <p>Our coffee is roasted in-house daily, and we offer a wide variety of coffee drinks, as well as pastries, sandwiches, and salads. 
       We also have a full bar, serving beer, wine, and cocktails.</p>
    <p>Our cafes are designed to be inviting and comfortable, and we offer free Wi-Fi and plenty of seating. We also have outdoor seating in our locations.</p>
    <p>We hope you'll come visit us soon and experience the Cafe23 difference!</p>
    <%= link_to 'Login', login_path, class: 'waves-effect waves-light btn' %>
    <br><br>
  <% end %>

</div>

app/views/home/privacy.html.erb
<div id="main_content">
  <h3>Cafe23 Privacy Policy</h3>
  <p>We're a quirky bunch here at Cafe23, and we like to keep things fun and light-hearted. 
  <p>That's why our private policy is just as quirky as we are.</p>
  <p>We promise to never share your personal information with anyone, unless it's absolutely necessary to do so (like if you order a coffee and we need to know your name). We also promise to never spam you, and we'll always respect your privacy.</p>
  <p>So come on in, relax, and enjoy a cup of coffee with us! We promise you won't be disappointed.</p>
</div>