config/routes.rb
Rails.application.routes.draw do
  
  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/search', to: 'home#search', as: :search

  # Authentication routes
  resources :sessions
  resources :users
  get 'employees/new', to: 'employees#new', as: :signup
  get 'employees/edit', to: 'employees#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  # Time Shifts routes
  get 'shifts/time_clock', to: 'shifts#time_clock', as: :time_clock
  patch 'shifts/time_in', to: 'shifts#time_in', as: :time_in
  patch 'shifts/time_out', to: 'shifts#time_out', as: :time_out
  # Payroll routes
  get 'payrolls/store_form', to: 'payrolls#store_form', as: :store_form
  get 'payrolls/employee_form', to: 'payrolls#employee_form', as: :employee_form
  get 'payrolls/employee_payroll', to: 'payrolls#employee_payroll', as: :employee_payroll
  get 'payrolls/store_payroll', to: 'payrolls#store_payroll', as: :store_payroll

  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :stores, except: [:destroy]
  resources :employees
  resources :assignments
  resources :shifts
  resources :shift_jobs, only: [:destroy]
  resources :jobs, except: [:show]
  resources :pay_grades, except: [:destroy]
  resources :pay_grade_rates

  # Other custom routes
  #get 'shift_today', to: 'shifts#route_clock', as: :shift_today_path
  get 'shift_jobs/new', to: 'shift_jobs#new', as: :new_shift_job
  post 'shift_jobs', to: 'shift_jobs#create', as: :shift_jobs

  # You can have the root of your site routed with 'root'
  root 'home#index'
  
end

app/models/shift.rb
class Shift < ApplicationRecord
  include Validations
  include Deletions

  # Relationships
  belongs_to :assignment
  has_one :employee, through: :assignment
  has_one :store, through: :assignment
  has_many :shift_jobs #, dependent: :destroy
  has_many :jobs, through: :shift_jobs

  # Enums
  enum :status, { pending: 1, started: 2, finished: 3 }, scopes: true, default: :pending

  # Scopes
  scope :completed,     -> { joins(:shift_jobs).group(:shift_id) }
  scope :incomplete,    -> { joins("LEFT JOIN shift_jobs ON shifts.id = shift_jobs.shift_id").where('shift_jobs.job_id IS NULL') }
  # alternative ways of finding 'incomplete' scope:
  # scope :incomplete,  -> { where('id NOT IN (?)', Shift.completed.map(&:id)) }
  # also see the class method 'not_completed' further on down...
  scope :for_store,     ->(store) { joins(:assignment, :store).where("assignments.store_id = ?", store.id) }
  scope :for_employee,  ->(employee) { joins(:assignment, :employee).where("assignments.employee_id = ?", employee.id) }
  scope :past,          -> { where('date < ?', Date.current) }
  scope :upcoming,      -> { where('date >= ?', Date.current) }
  scope :for_next_days, ->(x) { where('date BETWEEN ? AND ?', Date.current, x.days.from_now.to_date) }
  scope :for_past_days, ->(x) { where('date BETWEEN ? AND ?', x.days.ago.to_date, 1.day.ago.to_date) }
  scope :chronological, -> { order(:date, :start_time) }
  scope :by_store,      -> { joins(:assignment, :store).order(:name) }
  scope :by_employee,   -> { joins(:assignment, :employee).order(:last_name, :first_name) }
  # scope not in phase 3 requirements (b/c uses date range object)
  scope :for_dates,     ->(date_range) { where('date BETWEEN ? AND ?', date_range.start_date, date_range.end_date) }


  # Validations
  validates_date :date, on_or_after: lambda { :assignment_starts }, on_or_after_message: "must be on or after the start of the assignment"
  validates_time :start_time #, between: [Time.local(2000,1,1,11,0,0), Time.local(2000,1,1,23,0,0)]
  validates_time :end_time, after: :start_time, allow_blank: true
  validates_inclusion_of :status, in: statuses.keys, message: "is not an option"
  validate :assignment_must_be_current, on: :create
  validates_presence_of :assignment_id

  # Other methods
  def report_completed?
    self.shift_jobs.count > 0
  end
  
  # method uses the date_time_helpers gem; https://github.com/profh/time_date_helpers
  def duration
    (round_minutes(self.end_time) - round_minutes(self.start_time, direction: :down))/3600.0
  end
  
  # Callbacks
  # set default end_time (on create only)
  before_create :set_shift_end_time

  # allow shifts to only be deleted if status is 'pending'
  before_destroy do
    verify_shift_is_pending
    if errors.present?
      throw(:abort)
    end
  end

  # Misc Constants (for view dropdowns)
  STATUS_LIST = [['Pending', 'pending'],['Started', 'started'],['Finished', 'finished']].freeze


  private
  def assignment_starts
    @assignment_starts = self.assignment.start_date.to_date
  end
  
  def assignment_must_be_current
    return true if self.assignment.nil?
    unless self.assignment.end_date.nil?
      errors.add(:assignment_id, "is not a current assignment at the creamery")
    end
  end
  
  def set_shift_end_time
    return true unless self.end_time.nil? 
    self.end_time = self.start_time + (3*60*60)
  end

  def verify_shift_is_pending
    unless self.status == 'pending'
      errors.add(:base, "This shift either has begun or has finished and cannot be deleted.")
    end
  end
  
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :check_login
  authorize_resource

  def index
    @shifts = Shift.all
  end

  def show
    @shift = Shift.find(params[:id])
  end

  def new
    @shift = Shift.new
  end

  def create
    @shift = Shift.new(shift_params)
    if @shift.save
      redirect_to @shift, notice: 'Shift was successfully created.'
    else
      render :new
    end
  end

  def update
    @shift = Shift.find(params[:id])
    if @shift.update(shift_params)
      redirect_to @shift, notice: 'Shift was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @shift = Shift.find(params[:id])
    if @shift.destroy
      redirect_to shifts_url, notice: 'Shift was successfully destroyed.'
    else
      flash[:notice] = 'Shift could not be destroyed.'
      render :show
    end
  end

  def time_in
    @shift = current_user.shifts.find_by(date: Date.current)

    if @shift.present?
      TimeClock.new(@shift).start_shift_at(Time.now)
      flash[:notice] = "Your shift has started."
    else
      flash[:notice] = "You do not have any shifts today"
    end
  
    redirect_to home_path, notice: flash[:notice]
  end

  def time_out
    @shift = current_user.shifts.find_by(date: Date.current)

    if @shift.present?
      TimeClock.new(@shift).end_shift_at(Time.now)
      @shift.update(status: 3)
      flash[:notice] = "Your shift has ended."
    else
      flash[:notice] = "You do not have any shifts today"
    end
  
    redirect_to home_path, notice: flash[:notice]
  end

  def time_clock
    @shift_today = current_user.shifts.find_by(date: Date.current)

    if @shift_today.present?
      if @shift_today.started?
        # @clock_message = "Please clock in"
      end
    else
      flash[:notice] = "You do not have any shifts today"
      redirect_to home_path
    end
  end

  private
    def shift_params
      params.require(:shift).permit(:assignment_id, :date, :start_time, :end_time, :notes, :status)
    end
end

app/views/shifts/_shift_data.html.erb
<div class="card">
  <div class="card-content">
    <h5>Shift Information for <%= @shift.employee.name %></h5><br />

    <b>Shift Employee:&nbsp;&nbsp;</b>
      <%= @shift.employee.name %><br /><br />

    <b>Shift Date:&nbsp;&nbsp;</b>
      <%= @shift.date %><br /><br />

    <b>Start Time:&nbsp;&nbsp;</b>
      <%= @shift.start_time %><br /><br />

    <b>End Time:&nbsp;&nbsp;</b>
      <%= @shift.end_time %><br /><br />
    
    <b>Status:&nbsp;&nbsp;</b>
      <%= @shift.status %><br /><br />

    <b>Notes:&nbsp;&nbsp;</b>
      <%= @shift.notes %><br><br><br>
  
  </div>
</div>

app/views/shifts/_shift_fields.html.erb
<%= f.input :assignment_id, collection: Assignment.current.includes(:employee).map { |assignment| [assignment.employee.name, assignment.id] }, label: "Employee"  %>
<%= f.input :date, label_html: { class: 'active' } %>
<%= f.input :start_time, label_html: { class: 'active' } %>
<%= f.input :end_time, label_html: { class: 'active' } %>

app/views/shifts/_shift_sidebar.html.erb
<div class="card white lighten-4">
  <div class="card-content">
    <span class="card-title">Jobs Worked on Shift</span>
    <% unless @shift.shift_jobs.empty? %>
      <ul>
        <% for shift_job in @shift.shift_jobs %>
          <li>
            <% if can? :destroy, ShiftJob %>
              <%= link_to(shift_job_path(shift_job), class: 'remove', method: :delete) do %>
                x&nbsp;&nbsp;
              <% end %>
            <% end %>
            <%= link_to "#{shift_job.shift.date}, #{shift_job.job.name}", shift_job %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <% if can? :new, ShiftJob %>
    <div class="card-action">
      <% if @shift.finished? %>
        <%= link_to "Add Job to Shift", new_shift_job_path(job_id: @job), class: 'waves-effect waves-light btn' %>
      <% else %>
        <p>Jobs cannot be added without completing shift.</p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shifts/index.html.erb
<h2>Shifts</h2>
<% if can? :new, Shift %>
  <%= link_to "Add New Shift", new_shift_path, class: 'waves-effect waves-light btn' %> 
<% end %>

<h3>Upcoming Shifts</h3>
<h6>Shifts scheduled for today and future dates. 
    A shift that has finished today will not be moved to Completed Shifts until tomorrow.</h6>
<table>
  <thead>
    <tr>
      <th>Employee Name</th>
      <th>Date</th>
      <th>Start Time</th>
      <th>End Time</th>
    </tr>
  </thead>
  <tbody>
    <% @shifts.upcoming.each do |shift| %>
      <tr>
        <td><%= link_to "#{shift.employee.name}", shift_path(shift) %></td>
        <td><%= shift.date.strftime("%m/%d/%y") %></td>
        <td><%= shift.start_time.strftime("%H:%M") %></td>
        <td><%= shift.end_time.strftime("%H:%M") %></td>      
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Completed Shifts</h3>
<table>
  <thead>
    <tr>
      <th>Employee Name</th>
      <th>Date</th>
      <th>Start Time</th>
      <th>End Time</th>
    </tr>
  </thead>
  <tbody>
    <% @shifts.completed.each do |shift| %>
      <tr>
        <td><%= link_to "#{shift.employee.name}", shift_path(shift) %></td>
        <td><%= shift.date.strftime("%m/%d/%y") %></td>
        <td><%= shift.start_time.strftime("%H:%M") %></td>
        <td><%= shift.end_time.strftime("%H:%M") %></td>      
      </tr>
    <% end %>
  </tbody>
</table>

<h3> All Shift History </h3>
<table>
  <thead>
    <tr>
      <th>Employee Name</th>
      <th>Date</th>
      <th>Start Time</th>
      <th>End Time</th>
    </tr>
  </thead>
  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= link_to "#{shift.employee.name}", shift_path(shift) %></td>
        <td><%= shift.date.strftime("%m/%d/%y") %></td>
        <td><%= shift.start_time.strftime("%H:%M") %></td>
        <td><%= shift.end_time.strftime("%H:%M") %></td>      
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shifts/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @shift, 
                                                        type_of_form: "New Shift",
                                                        fields: "shift_fields"} %>

app/views/shifts/show.html.erb
<%= render partial: "partials/show_structure", locals: {model_name: "shift", 
                                                         object: @shift,
                                                         primary: "shift_data", 
                                                         secondary: nil,
                                                         sidebar: "shift_sidebar"} %>